[target.x86_64-unknown-linux-gnu]
rustflags = [
    # LLD is generally faster and might be the default for Rust in the future.
    # See here: https://github.com/rust-lang/rust/issues/71515
    #
    # skylake CPU family includes most SSE and AVX2 instructions from about 10 years ago
    # without this, optimization cannot use almost any vector instructions, unless
    # you explicitly set target-cpu yourself when building.
    "-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=skylake"
]
